[package]
name = "simple-ops"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
math-ops = { git = "https://github.com/dmohindru/rust-projects", branch = "main", package = "math-ops", features = [
    "sum",
    "sub",
] }
